---
name: "Setup Piet"
author: Yevhen Fabizhevskyi
description: "This GitHub action installs one of the Piet Programming Language interpreters called npiet."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: npiet interpreter version.
    required: false
    default: "1.3f"
  force:
    description: |
      If "false" skips installation if npiet is already installed. If "true"
      installs npiet in any case. Defaults to "false".
    required: false
    default: "false"
outputs:
  installed:
    description: Whether npiet was installed or not.
    value: "${{ steps.install-npiet.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      env:
        INPUT_VERSION: "${{ inputs.version }}"
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./validate-inputs.sh "${INPUT_VERSION}" "${INPUT_FORCE}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Install libpng
      run: ${{ case(runner.os == 'Linux', 'sudo apt-get install -y libpng-dev', runner.os == 'Windows', 'choco install libpng -y', 'brew install libpng') }} # yamllint disable-line
      shell: ${{ case(runner.os == 'Windows', 'pwsh', 'sh') }}

    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./collect-info.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Install npiet
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-npiet
      env:
        INPUT_VERSION: "${{ inputs.version }}"
        STEP_INFO_OUTPUT_BIN_PATH: "${{ steps.info.outputs.bin-path }}"
      run: ./install-npiet.sh "${INPUT_VERSION}" "${STEP_INFO_OUTPUT_BIN_PATH}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Print location
      run: |
        . ./logging.sh
        log_info "npiet is located at $(which npiet)"
      shell: sh
      working-directory: "${{ github.action_path }}/src/lib"
