---
name: 'Setup Pier'
author: Yevhen Fabizhevskyi
description: 'This GitHub action installs one of the Pier Programming Language interpreters called npiet.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'npiet interpreter version.'
    required: false
    default: '1.3'
runs:
  using: 'composite'
  steps:
    - name: Fail
      uses: actions/github-script@v6
      if: ${{ runner.os != 'Windows' }}
      with:
        script: core.setFailed('${{ runner.os }} ${{ runner.arch }} is not supported');
    - name: Collect info
      if: ${{ runner.os == 'Windows' }}
      id: info
      run: |
        NPIET_INSTALLED=$(if command -v npiet >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "NPIET_INSTALLED=$NPIET_INSTALLED" >> $GITHUB_OUTPUT
        mkdir -p "$GITHUB_WORKSPACE/npiet"
        echo "NPIET_PATH=$GITHUB_WORKSPACE/npiet" >> $GITHUB_OUTPUT
      shell: sh
    - name: Install npiet
      if: ${{ steps.info.outputs.NPIET_INSTALLED == 'false' && runner.os == 'Windows' }}
      run: |
        if ("${{ inputs.version }}" -eq "1.1") {
          $Version="${{ inputs.version }}"
        } else {
          $Version="${{ inputs.version }}a"
        }
        Invoke-WebRequest -URI "http://www.bertnase.de/npiet/npiet-$Version-win32.zip" -OutFile npiet.zip
        Expand-Archive npiet.zip -DestinationPath .
        Remove-Item -Path npiet.zip
        echo "${{ steps.info.outputs.NPIET_PATH }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh
      working-directory: ${{ steps.info.outputs.NPIET_PATH }}
