---
name: "Setup Piet"
author: Yevhen Fabizhevskyi
description: "This GitHub action installs one of the Piet Programming Language interpreters called npiet."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: npiet interpreter version.
    required: false
    default: "1.3"
  force:
    description: |
      If "false" skips installation if npiet is already installed. If "true"
      installs npiet in any case. Defaults to "false".
    required: false
    default: "false"
outputs:
  installed:
    description: Whether npiet was installed or not.
    value: "${{ steps.install-npiet.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os != 'Windows' }}
      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
      shell: sh

    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./collect-info.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Install npiet
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-npiet
      env:
        INPUT_VERSION: "${{ inputs.version }}"
      run: |
        .\install-npiet.ps1 `
          "$Env:INPUT_VERSION" `
          "${{ steps.info.outputs.bin-dir }}" `
          "${{ steps.info.outputs.bin-path }}"
      shell: pwsh

    - name: Print version
      run: npiet -v
      shell: sh
