---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "action.yml"
      - "hi.png"
      - ".github/workflows/functional-tests.yml"
  push:
    branches:
      - "main"

defaults:
  run:
    shell: sh

jobs:
  run-script:
    name: Run script
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        version: ["1.1", "1.3"]
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Setup Piet
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Run script
        run: npiet hi.png
