---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/functional-tests.yml
      - src/**
      - hi.png
      - action.yml
  schedule:
    # Every Friday at 09:00 JST
    - cron: "0 0 * * 5"
  workflow_dispatch: {}

defaults:
  run:
    shell: sh

jobs:
  run-script:
    name: Run script
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        version: ["1.1", "1.3"]
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v5
      - name: Setup Piet
        id: setup-piet
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Test action completion
        run: |
          test_equal() {
            if [ "${2}" != "${3}" ]; then
              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
              exit 1
            fi
          }
          test_equal "npiet should be installed" \
            "${{ steps.setup-piet.outputs.installed }}" \
            "true"
      - name: Validate command
        run: |
          [ "$(npiet hi.png)" = "Hi" ] || exit 1
  test-force:
    name: Test force
    runs-on: windows-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        force: ["true", "false"]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v5
      - name: Setup piet 1
        id: setup-piet-1
        uses: ./
      - name: Setup piet 2
        id: setup-piet-2
        uses: ./
        with:
          force: ${{ matrix.force }}
      - name: Test action completion
        run: |
          test_equal() {
            if [ "${2}" != "${3}" ]; then
              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
              exit 1
            fi
          }
          test_equal "Wrong \"installed\" output from setup-piet-1" \
            "${{ steps.setup-piet-1.outputs.installed }}" \
            "true"
          test_equal "Wrong \"installed\" output from setup-piet-2" \
            "${{ steps.setup-piet-2.outputs.installed }}" \
            "${{ matrix.force }}"
