---
name: Functional Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  run-script:
    name: Run script
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
        version: ['1.1', '1.3']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Run script
        run: npiet hi.png
        shell: sh
