---
name: Functional Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/functional-tests.yml
      - src/**
      - hi.png
      - action.yml
  schedule:
    # Every Friday at 09:00 JST
    - cron: "0 0 * * 5"
  workflow_dispatch: {}

defaults:
  run:
    shell: sh

jobs:
  run-script:
    name: Run script
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "windows", "macos"]
        version: ["1.2a", "1.2b", "1.3f"]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7
        with:
          persist-credentials: "false"
      - name: Install libpng
        run: ${{ case(matrix.os == 'ubuntu', 'sudo apt-get install -y libpng-dev', matrix.os == 'macos', 'brew install libpng', 'choco install libpng -y') }} # yamllint disable-line
        shell: sh
      - name: Setup Piet
        id: setup-piet
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Test action completion
        env:
          STEP_SETUP_PIET_OUTPUT_INSTALLED: "${{ steps.setup-piet.outputs.installed }}"
        run: |
          test_equal() {
            if [ "${2}" != "${3}" ]; then
              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
              exit 1
            fi
          }
          test_equal "npiet should be installed" \
            "${STEP_SETUP_PIET_OUTPUT_INSTALLED}" \
            "true"
      - name: Validate command
        run: |
          [ "$(npiet hi.png)" = "Hi" ] || exit 1
  test-force:
    name: Test force
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        force: ["true", "false"]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v7
        with:
          persist-credentials: "false"
      - name: Setup piet 1
        id: setup-piet-1
        uses: ./
      - name: Setup piet 2
        id: setup-piet-2
        uses: ./
        with:
          force: ${{ matrix.force }}
      - name: Test action completion
        env:
          STEP_SETUP_PIET_1_OUTPUT_INSTALLED: "${{ steps.setup-piet-1.outputs.installed }}"
          STEP_SETUP_PIET_2_OUTPUT_INSTALLED: "${{ steps.setup-piet-2.outputs.installed }}"
        run: |
          test_equal() {
            if [ "${2}" != "${3}" ]; then
              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
              exit 1
            fi
          }
          test_equal "Wrong \"installed\" output from setup-piet-1" \
            "${STEP_SETUP_PIET_1_OUTPUT_INSTALLED}" \
            "true"
          test_equal "Wrong \"installed\" output from setup-piet-2" \
            "${STEP_SETUP_PIET_2_OUTPUT_INSTALLED}" \
            "${{ matrix.force }}"
